// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import StoreProvider from "@/components/storeProvider";
// import { ThemeProvider } from "next-themes";
// import { AuthProvider } from "@/components/auth-provider";
// import { Toaster } from "@/components/ui/sonner";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// export default function RootLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode;
// }>) {
//     return (
//         <html lang="en" suppressHydrationWarning={true}>
//             <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//                 <ThemeProvider
//                     attribute="class"
//                     defaultTheme="light"
//                     enableSystem
//                     disableTransitionOnChange
//                 >
//                     <StoreProvider>
//                         <AuthProvider>
//                             {children}
//                             <Toaster />
//                         </AuthProvider>
//                     </StoreProvider>
//                 </ThemeProvider>
//             </body>
//         </html>
//     );
// }

import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google"; // 1. Import the right fonts
import "./globals.css";
import StoreProvider from "@/components/storeProvider";
import { ThemeProvider } from "next-themes";
import { AuthProvider } from "@/components/auth-provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
    display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
    subsets: ["latin"],
    variable: "--font-jetbrains-mono",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Dokit - Collaborative Code Editor",
    description: "Real-time collaborative code editor",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.variable} ${jetbrainsMono.variable} antialiased font-sans`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    <StoreProvider>
                        <AuthProvider>
                            {children}
                            <Toaster position="top-right" richColors={true} />
                        </AuthProvider>
                    </StoreProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
