version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres_db
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    networks: 
      - dokit-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_gui
    restart: always
    ports:
      - '127.0.0.1:5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks: 
      - dokit-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - '127.0.0.1:6379:6379'
    networks: 
      - dokit-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - '127.0.0.1:11434:11434'
    networks: 
      - dokit-network
    volumes:
      - ollama_data:/root/.ollama

  dokit-nginx:
    image: dokit-nginx:latest
    container_name: nginx-dokit
    ports:
      - '8080:80'
    environment:
      - BACKEND_URL=http://172.17.0.1:4000
      - DOMAIN=dokit.backends.live
      - DOMAIN_ESCAPED=dokit\.backends\.live
    networks: 
      - dokit-network
      - dokit-project-network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
  redis-data:
  ollama_data:
networks:
  dokit-network:
    external: true 
  dokit-project-network:
    external: true